// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rexec/v1/agent.proto

package rexecv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_rexec_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	CaPem         []byte                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_rexec_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type IdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRequest) Reset() {
	*x = IdentityRequest{}
	mi := &file_rexec_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRequest) ProtoMessage() {}

func (x *IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRequest.ProtoReflect.Descriptor instead.
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{2}
}

type IdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResponse) Reset() {
	*x = IdentityResponse{}
	mi := &file_rexec_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponse) ProtoMessage() {}

func (x *IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponse.ProtoReflect.Descriptor instead.
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *IdentityResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_rexec_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{4}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_rexec_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *InfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_rexec_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ExecChunk is one streamed unit of a running command: a slice of stdout or
// stderr, the final exit code, or (P4) a request for the caller to approve a
// destructive operation before it proceeds.
type ExecChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecChunk_Stdout
	//	*ExecChunk_Stderr
	//	*ExecChunk_ExitCode
	//	*ExecChunk_NeedsApproval
	Msg           isExecChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecChunk) Reset() {
	*x = ExecChunk{}
	mi := &file_rexec_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecChunk) ProtoMessage() {}

func (x *ExecChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecChunk.ProtoReflect.Descriptor instead.
func (*ExecChunk) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecChunk) GetMsg() isExecChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecChunk) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecChunk_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecChunk) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecChunk_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecChunk) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Msg.(*ExecChunk_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *ExecChunk) GetNeedsApproval() *ApprovalRequest {
	if x != nil {
		if x, ok := x.Msg.(*ExecChunk_NeedsApproval); ok {
			return x.NeedsApproval
		}
	}
	return nil
}

type isExecChunk_Msg interface {
	isExecChunk_Msg()
}

type ExecChunk_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecChunk_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecChunk_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type ExecChunk_NeedsApproval struct {
	NeedsApproval *ApprovalRequest `protobuf:"bytes,4,opt,name=needs_approval,json=needsApproval,proto3,oneof"`
}

func (*ExecChunk_Stdout) isExecChunk_Msg() {}

func (*ExecChunk_Stderr) isExecChunk_Msg() {}

func (*ExecChunk_ExitCode) isExecChunk_Msg() {}

func (*ExecChunk_NeedsApproval) isExecChunk_Msg() {}

type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`                     // human-readable description of what will run
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                           // why approval is required (policy said "ask")
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"` // one-time id the controller must echo back to proceed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_rexec_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rexec_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_rexec_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApprovalRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

var File_rexec_v1_agent_proto protoreflect.FileDescriptor

const file_rexec_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14rexec/v1/agent.proto\x12\brexec.v1\">\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\"\x8c\x01\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\"\x11\n" +
	"\x0fIdentityRequest\"O\n" +
	"\x10IdentityResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\"\r\n" +
	"\vInfoRequest\"h\n" +
	"\fInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xc6\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.rexec.v1.ExecRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\tExecChunk\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x12B\n" +
	"\x0eneeds_approval\x18\x04 \x01(\v2\x19.rexec.v1.ApprovalRequestH\x00R\rneedsApprovalB\x05\n" +
	"\x03msg\"h\n" +
	"\x0fApprovalRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId2\xac\x02\n" +
	"\x05Agent\x12;\n" +
	"\x06Enroll\x12\x17.rexec.v1.EnrollRequest\x1a\x18.rexec.v1.EnrollResponse\x12A\n" +
	"\bIdentity\x12\x19.rexec.v1.IdentityRequest\x1a\x1a.rexec.v1.IdentityResponse\x125\n" +
	"\x04Info\x12\x15.rexec.v1.InfoRequest\x1a\x16.rexec.v1.InfoResponse\x124\n" +
	"\x04Exec\x12\x15.rexec.v1.ExecRequest\x1a\x13.rexec.v1.ExecChunk0\x01\x126\n" +
	"\x06Deploy\x12\x15.rexec.v1.ExecRequest\x1a\x13.rexec.v1.ExecChunk0\x01B@Z>github.com/inovacc/remote-exec/internal/proto/rexec/v1;rexecv1b\x06proto3"

var (
	file_rexec_v1_agent_proto_rawDescOnce sync.Once
	file_rexec_v1_agent_proto_rawDescData []byte
)

func file_rexec_v1_agent_proto_rawDescGZIP() []byte {
	file_rexec_v1_agent_proto_rawDescOnce.Do(func() {
		file_rexec_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rexec_v1_agent_proto_rawDesc), len(file_rexec_v1_agent_proto_rawDesc)))
	})
	return file_rexec_v1_agent_proto_rawDescData
}

var file_rexec_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rexec_v1_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),    // 0: rexec.v1.EnrollRequest
	(*EnrollResponse)(nil),   // 1: rexec.v1.EnrollResponse
	(*IdentityRequest)(nil),  // 2: rexec.v1.IdentityRequest
	(*IdentityResponse)(nil), // 3: rexec.v1.IdentityResponse
	(*InfoRequest)(nil),      // 4: rexec.v1.InfoRequest
	(*InfoResponse)(nil),     // 5: rexec.v1.InfoResponse
	(*ExecRequest)(nil),      // 6: rexec.v1.ExecRequest
	(*ExecChunk)(nil),        // 7: rexec.v1.ExecChunk
	(*ApprovalRequest)(nil),  // 8: rexec.v1.ApprovalRequest
	nil,                      // 9: rexec.v1.ExecRequest.EnvEntry
}
var file_rexec_v1_agent_proto_depIdxs = []int32{
	9, // 0: rexec.v1.ExecRequest.env:type_name -> rexec.v1.ExecRequest.EnvEntry
	8, // 1: rexec.v1.ExecChunk.needs_approval:type_name -> rexec.v1.ApprovalRequest
	0, // 2: rexec.v1.Agent.Enroll:input_type -> rexec.v1.EnrollRequest
	2, // 3: rexec.v1.Agent.Identity:input_type -> rexec.v1.IdentityRequest
	4, // 4: rexec.v1.Agent.Info:input_type -> rexec.v1.InfoRequest
	6, // 5: rexec.v1.Agent.Exec:input_type -> rexec.v1.ExecRequest
	6, // 6: rexec.v1.Agent.Deploy:input_type -> rexec.v1.ExecRequest
	1, // 7: rexec.v1.Agent.Enroll:output_type -> rexec.v1.EnrollResponse
	3, // 8: rexec.v1.Agent.Identity:output_type -> rexec.v1.IdentityResponse
	5, // 9: rexec.v1.Agent.Info:output_type -> rexec.v1.InfoResponse
	7, // 10: rexec.v1.Agent.Exec:output_type -> rexec.v1.ExecChunk
	7, // 11: rexec.v1.Agent.Deploy:output_type -> rexec.v1.ExecChunk
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rexec_v1_agent_proto_init() }
func file_rexec_v1_agent_proto_init() {
	if File_rexec_v1_agent_proto != nil {
		return
	}
	file_rexec_v1_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecChunk_Stdout)(nil),
		(*ExecChunk_Stderr)(nil),
		(*ExecChunk_ExitCode)(nil),
		(*ExecChunk_NeedsApproval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rexec_v1_agent_proto_rawDesc), len(file_rexec_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rexec_v1_agent_proto_goTypes,
		DependencyIndexes: file_rexec_v1_agent_proto_depIdxs,
		MessageInfos:      file_rexec_v1_agent_proto_msgTypes,
	}.Build()
	File_rexec_v1_agent_proto = out.File
	file_rexec_v1_agent_proto_goTypes = nil
	file_rexec_v1_agent_proto_depIdxs = nil
}
